package com.myProject.eventPlatform.enumuration.responseModel;

public enum ResponseMessageEnum {

    LISTING_SUCCESSFULLY_DONE,
    DATA_NOT_FOUND,
    CREATED_SUCCESSFULLY,
    CREATED_ERROR,
    UPDATED_SUCCESSFULLY_DONE,
    UPDATED_ERROR,
    DELETED_SUCCESSFULLY_DONE,
    DELETED_ERROR,
    CONNECTION_ACCEPTED,
    CONNECTION_REJECT,
    CONNECTION_ACCEPT_ERROR,
    CONNECTION_ALREADY_ACCEPT;









}
